spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # dev como padrão
  application:
    name: curso  # Nome do microsserviço
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: derich.rosario22@gmail.com
    password: ${password}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8082  # Porta do microsserviço

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

aws:
  region: sa-east-1
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}
  bucketName: plataforma-cursos-bucket-sp
  profileName: default

stripe:
  secret:
    key: ${STRIPE_KEY}

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    io.micrometer.tracing: DEBUG
    io.opentelemetry: DEBUG


