spring:
  rabbitmq:
    uri: ${RABBITMQ_URL}
  data:
    mongodb:
      uri: ${MONGODB_CURSO_URI}
elasticsearch:
  uris: ${ELASTIC_URI}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}