spring:
  application:
    name: Usuario  # Nome do microsserviço
    mongodb:
      database: usuario  # Banco de dados MongoDB do microsserviço
      uri: ${MONGODB_USUARIO}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8081  # Porta do microsserviço

secret:
  key: ${SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

logging:
  level:
    root: INFO