spring:
  application:
    name: Usuario  # Nome do microsserviço
    mongodb:
      database: usuario  # Banco de dados MongoDB do microsserviço
      uri: ${MONGODB_USUARIO}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8081  # Porta do microsserviço

secret:
  key: ${SECRET_KEY}

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    io.micrometer.tracing: DEBUG
    io.opentelemetry: DEBUG